apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: giovanamachado-playlist-recommender
  namespace: argocd
spec:
  # Project this application belongs to
  project: giovanamachado-project
  
  # Source repository configuration
  source:
    # IMPORTANT: Update this to your Git repository URL
    repoURL: https://github.com/Giovana2ma/playlist-recommender.git
    targetRevision: HEAD  # Can also use a specific branch, tag, or commit
    path: .  # Path to Kubernetes manifests (use . if in root directory)
  
  # Destination cluster and namespace
  destination:
    server: https://kubernetes.default.svc
    namespace: giovanamachado
  
  # Sync policy - automatic sync and prune
  syncPolicy:
    automated:
      prune: true      # Automatically delete resources that are no longer in Git
      selfHeal: true   # Automatically sync when cluster state differs from Git
      allowEmpty: false
    syncOptions:
      - CreateNamespace=false  # Namespace should already exist
      - PrunePropagationPolicy=foreground
      - PruneLast=true  # Prune resources as the last step
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  # Ignore differences in certain fields
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas  # Ignore replica count differences (useful if using HPA)
