apiVersion: batch/v1
kind: CronJob
metadata:
  name: ml-model-updater
  namespace: giovanamachado
spec:
  # Check for dataset changes every 5 minutes
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 600
      template:
        metadata:
          labels:
            app: ml-model-updater
        spec:
          serviceAccountName: ml-updater-sa
          restartPolicy: Never
          containers:
          - name: updater
            image: bitnami/kubectl:latest
            command:
            - /bin/bash
            - -c
            - |
              #!/bin/bash
              set -e
              
              echo "=== ML Model Updater ==="
              echo "Checking for dataset changes..."
              
              # Get current dataset from ConfigMap
              DATASET_URL=$(kubectl get configmap playlist-config -n giovanamachado -o jsonpath='{.data.DATASET_URL}')
              DATASET_NAME=$(kubectl get configmap playlist-config -n giovanamachado -o jsonpath='{.data.DATASET_NAME}')
              MODEL_FILENAME=$(kubectl get configmap playlist-config -n giovanamachado -o jsonpath='{.data.MODEL_FILENAME}')
              
              echo "Current dataset: $DATASET_NAME"
              echo "Dataset URL: $DATASET_URL"
              echo "Model file: $MODEL_FILENAME"
              
              # Generate unique job name based on dataset and timestamp
              TIMESTAMP=$(date +%Y%m%d-%H%M%S)
              JOB_NAME="ml-job-${DATASET_NAME}-${TIMESTAMP}"
              
              # Check if a job is already running for this dataset
              RUNNING_JOBS=$(kubectl get jobs -n giovanamachado -l dataset=${DATASET_NAME} --field-selector status.successful!=1 -o name | wc -l)
              
              if [ "$RUNNING_JOBS" -gt 0 ]; then
                echo "A job is already running for dataset ${DATASET_NAME}, skipping..."
                exit 0
              fi
              
              # Check if model file exists and is recent (less than 1 hour old)
              POD_NAME=$(kubectl get pods -n giovanamachado -l app=giovanamachado-playlist-recommender -o jsonpath='{.items[0].metadata.name}')
              if [ -n "$POD_NAME" ]; then
                MODEL_AGE=$(kubectl exec -n giovanamachado $POD_NAME -- sh -c "test -f /model/$MODEL_FILENAME && echo found || echo notfound" 2>/dev/null || echo "notfound")
                
                if [ "$MODEL_AGE" = "found" ]; then
                  echo "Model file exists, checking if rebuild needed..."
                  # In production, you'd check file age or hash here
                  # For now, we'll skip if the file exists
                  # Uncomment the line below to always regenerate
                  # MODEL_AGE="notfound"
                fi
                
                if [ "$MODEL_AGE" = "found" ]; then
                  echo "Model is up to date, no rebuild needed."
                  exit 0
                fi
              fi
              
              echo "Creating new ML job: $JOB_NAME"
              
              # Create the job dynamically
              cat <<EOF | kubectl apply -f -
              apiVersion: batch/v1
              kind: Job
              metadata:
                name: ${JOB_NAME}
                namespace: giovanamachado
                labels:
                  app: giovanamachado-playlist-ml
                  dataset: ${DATASET_NAME}
                  managed-by: ml-model-updater
              spec:
                ttlSecondsAfterFinished: 3600
                template:
                  metadata:
                    labels:
                      app: giovanamachado-playlist-ml
                  spec:
                    restartPolicy: Never
                    containers:
                    - name: ml-generator
                      image: docker.io/giovana2ma/playlists-ml:0.1
                      imagePullPolicy: IfNotPresent
                      command: ["python3", "ruleGenerator.py"]
                      args:
                        - "\$(DATASET_PATH)"
                        - "-o"
                        - "/output/\$(MODEL_FILENAME)"
                        - "-s"
                        - "\$(MIN_SUPPORT)"
                        - "-c"
                        - "\$(MIN_CONFIDENCE)"
                        - "-l"
                        - "\$(MIN_LIFT)"
                      env:
                      - name: DATASET_PATH
                        valueFrom:
                          configMapKeyRef:
                            name: playlist-config
                            key: DATASET_URL
                      - name: MODEL_FILENAME
                        valueFrom:
                          configMapKeyRef:
                            name: playlist-config
                            key: MODEL_FILENAME
                      - name: MIN_SUPPORT
                        valueFrom:
                          configMapKeyRef:
                            name: playlist-config
                            key: MIN_SUPPORT
                      - name: MIN_CONFIDENCE
                        valueFrom:
                          configMapKeyRef:
                            name: playlist-config
                            key: MIN_CONFIDENCE
                      - name: MIN_LIFT
                        valueFrom:
                          configMapKeyRef:
                            name: playlist-config
                            key: MIN_LIFT
                      volumeMounts:
                      - name: dataset-volume
                        mountPath: /home/datasets/spotify
                        readOnly: true
                      - name: model-volume
                        mountPath: /output
                    volumes:
                    - name: dataset-volume
                      hostPath:
                        path: /home/datasets/spotify
                        type: Directory
                    - name: model-volume
                      persistentVolumeClaim:
                        claimName: project2-pvc
              EOF
              
              echo "Job created successfully: $JOB_NAME"
              
              # Trigger deployment restart to pick up new model
              echo "Triggering deployment restart..."
              kubectl rollout restart deployment/playlist-recommender -n giovanamachado
              
              echo "=== Update complete ==="
