apiVersion: batch/v1
kind: Job
metadata:
  # IMPORTANT: Change the name when dataset changes to force new Job creation
  # Format: ml-job-<dataset>-<timestamp-or-version>
  name: ml-job-ds1-v1
  namespace: giovanamachado
  labels:
    app: giovanamachado-playlist-ml
    dataset: ds1
spec:
  # Automatically clean up finished jobs after 1 hour
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        app: giovanamachado-playlist-ml
    spec:
      restartPolicy: Never
      containers:
      - name: ml-generator
        image: docker.io/giovana2ma/playlists-ml:0.1
        imagePullPolicy: IfNotPresent
        
        # Command to run the rule generator
        command: ["python3", "ruleGenerator.py"]
        args:
          - "$(DATASET_PATH)"
        
        # Environment variables from ConfigMap
        env:
        - name: DATASET_PATH
          valueFrom:
            configMapKeyRef:
              name: playlist-config
              key: DATASET_URL
        
        volumeMounts:
        # Mount the dataset directory (read-only)
        - name: dataset-volume
          mountPath: /home/datasets/spotify
          readOnly: true
        # Mount the PVC for output (read-write)
        - name: model-volume
          mountPath: /output
      
      volumes:
      # Host path to dataset directory
      - name: dataset-volume
        hostPath:
          path: /home/datasets/spotify
          type: Directory
      # Persistent volume claim for model storage
      - name: model-volume
        persistentVolumeClaim:
          claimName: project2-pvc
